### ISSUE TITLE
企业微信同步问题，只同步了部分部分，docker-compose

### ISSUE THREAD

**Issue by so-easy** [dromara/MaxKey#218]
2024-03-28 16:56:04.982 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.updateSyncTime:135 - ==>  Preparing: update mxk_synchro_related set synctime = ? where id= ?
2024-03-28 16:56:04.983 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.updateSyncTime:135 - ==> Parameters: 2024-03-28 16:56:04(String), 970763277137084416(String)
2024-03-28 16:56:04.988 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.updateSyncTime:135 - <==    Updates: 1
2024-03-28 16:56:04.988 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.synchronizer.workweixin.WorkweixinOrganizationService:49 - dept : 46 社群运营 47
2024-03-28 16:56:04.988 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.find:135 - ==>  Preparing: SELECT sel_tmp_table.* FROM mxk_synchro_related sel_tmp_table WHERE (instid = '1' and syncId = '4' and originid = '46' and objecttype = 'Organization')
2024-03-28 16:56:04.988 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.find:135 - ==> Parameters: 
2024-03-28 16:56:04.988 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.find:135 - <==      Total: 0
2024-03-28 16:56:04.989 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.find:135 - ==>  Preparing: SELECT sel_tmp_table.* FROM mxk_synchro_related sel_tmp_table WHERE (instid = '1' and syncId = '4' and originid = '47' and objecttype = 'Organization')
2024-03-28 16:56:04.989 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.find:135 - ==> Parameters: 
2024-03-28 16:56:04.989 DEBUG [http-nio-9526-exec-8] org.dromara.maxkey.persistence.mapper.SynchroRelatedMapper.find:135 - <==      Total: 0
java.lang.NullPointerException: Cannot invoke "org.dromara.maxkey.entity.SynchroRelated.getObjectId()" because "synchroRelatedParent" is null
	at org.dromara.maxkey.synchronizer.workweixin.WorkweixinOrganizationService.buildOrganization(WorkweixinOrganizationService.java:120)
	at org.dromara.maxkey.synchronizer.workweixin.WorkweixinOrganizationService.sync(WorkweixinOrganizationService.java:62)
	at org.dromara.maxkey.synchronizer.workweixin.WorkweixinSynchronizerService.sync(WorkweixinSynchronizerService.java:53)
	at org.dromara.maxkey.web.config.contorller.SynchronizersController.synchr(SynchronizersController.java:95)
	at jdk.internal.reflect.GeneratedMethodAccessor748.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)

**Comment by so-easy** [comment]
<img width="1169" alt="image" src="https://github.com/dromara/MaxKey/assets/7981458/f661a684-9b05-4fe1-9516-42474e5bdeac">
![1711621879850](https://github.com/dromara/MaxKey/assets/7981458/a252048b-09be-4ceb-91cf-7179216f2e2a)
![Uploading 1711621918612.jpg…]()

**Comment by so-easy** [comment]
![Uploading 1711621918612.jpg…]()

**Comment by so-easy** [comment]
Preparing: UPDATE mxk_organizations SET orgcode = ? , orgname = ? , parentid = ? , parentname = ? , level = ? , sortindex = ? , description = ? , status = ? , instid = ? WHERE (id = ?)
 
![Uploading 企业微信截图_72805c42-bb89-4c07-b17b-66c01a7ba857.png…]()

**Comment by so-easy** [comment]
<img width="854" alt="企业微信截图_72805c42-bb89-4c07-b17b-66c01a7ba857" src="https://github.com/dromara/MaxKey/assets/7981458/2fa04e2b-0d87-414a-a6cf-2a60f948bfa0">
Preparing: UPDATE mxk_organizations SET orgcode = ? , orgname = ? , parentid = ? , parentname = ? , level = ? , sortindex = ? , description = ? , status = ? , instid = ? WHERE (id = ?)

更新组织部门，缺少type 类型，，页面少一列，而且无法全部同步

**Comment by yumu7777777** [comment]
![image](https://github.com/dromara/MaxKey/assets/104643678/c563ead3-fcc2-46ed-8c1c-239a72041587)  您好！企业微信扫码登录你配置过吗？为啥我的是404

**Comment by shimingxy** [comment]
请使用最新版本4.1.x进行测试验证，并重新开新的issue
