### ISSUE TITLE
上下文sign异常

### ISSUE THREAD

**Issue by hugoren** [dromara/MaxKey#98]
版本： 3.5.9
部署方式： docker-compose
问题：配置jenkins cas，跳转失败，提示/securityRealm/finishLogin not registered
查看日志：  Nov 23, 2022 12:00:45 PM org.apache.catalina.core.StandardWrapperValve invoke
maxkey                 | SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [/sign] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
maxkey                 | java.lang.NullPointerException
maxkey                 |        at java.util.Objects.requireNonNull(Objects.java:203)
maxkey                 |        at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2019)
maxkey                 |        at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1993)
maxkey                 |        at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:130)
maxkey                 |        at org.maxkey.persistence.service.AppsService.get(AppsService.java:83)
maxkey                 |        at org.maxkey.persistence.service.AppsService$$FastClassBySpringCGLIB$$27fef312.invoke(<generated>)
maxkey                 |        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
maxkey                 |        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
maxkey                 |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
maxkey                 |        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
maxkey                 |        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
maxkey                 |        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
maxkey                 |        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
maxkey                 |        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
maxkey                 |        at org.maxkey.persistence.service.AppsService$$EnhancerBySpringCGLIB$$dbcaf35c.get(<generated>)
maxkey                 |        at org.maxkey.authz.endpoint.AuthorizeBaseEndpoint.getApp(AuthorizeBaseEndpoint.java:62)
maxkey                 |        at org.maxkey.authz.endpoint.AuthorizeEndpoint.authorize(AuthorizeEndpoint.java:61)
maxkey                 |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
maxkey                 |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
maxkey                 |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
maxkey                 |        at java.lang.reflect.Method.invoke(Method.java:498)
maxkey                 |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
maxkey                 |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
maxkey                 |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
maxkey                 |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
maxkey                 |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
maxkey                 |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
maxkey                 |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
maxkey                 |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
maxkey                 |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
maxkey                 |        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
maxkey                 |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
maxkey                 |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
maxkey                 |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.maxkey.web.WebInstRequestFilter.doFilter(WebInstRequestFilter.java:80)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.maxkey.web.WebXssRequestFilter.doFilter(WebXssRequestFilter.java:98)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
maxkey                 |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
maxkey                 |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
maxkey                 |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
maxkey                 |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
maxkey                 |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
maxkey                 |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
maxkey                 |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
maxkey                 |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
maxkey                 |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
maxkey                 |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
maxkey                 |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
maxkey                 |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
maxkey                 |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
maxkey                 |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
maxkey                 |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
maxkey                 |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
maxkey                 |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
maxkey                 |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
maxkey                 |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
maxkey                 |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
maxkey                 |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
maxkey                 |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
maxkey                 |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
maxkey                 |        at java.lang.Thread.run(Thread.java:748)

**Comment by lihumzsan** [comment]
追问下这个报错是怎么解决的，我也遇到了

**Comment by shimingxy** [comment]
问题：配置jenkins cas，跳转失败，提示/securityRealm/finishLogin not registered
解决:   请先注册CAS应用，应用地址需要先再maxkey配置
